 XDataPlayerConfig:
  ServerIP: 127.0.0.1
  Port: 6000
  MarketServer: MarketServer
  TickerListPath: /
  BackTest: false
  MarketDataPath: /tmp/MarketData
  IntervalMS : 1
  BeginDay : 2021-12-27
  EndDay: 2022-01-04
